# Generated by Django 6.1.1 on 2026-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('class_name', models.CharField(blank=True, help_text='Example: Primary, Middle School, Class 9-10', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('subjects', models.TextField(blank=True, help_text='Write subjects separated by commas.')),
                ('highlights', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academics/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('icon', models.CharField(blank=True, help_text='Optional icon name for frontend use.', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('notice_date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('is_important', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-notice_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='classes',
            field=models.CharField(blank=True, help_text='Example: Classes 0 to 10', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
