# Generated by Django 6.1.1 on 2026-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_academicprogram_achievement_facility_notice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='subjects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
